[programs.devnet]
gifprograms = "9BNVHqRvQxAzwgR53bUYFSmE8sXAq9oQB9EtAa9Py3qX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/swarnab/.config/solana/id.json"

[scripts]
test = "node tests/gifprograms.js"
